spring.application.name=ecom

spring.datasource.url=jdbc:h2:mem:testdb

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

project.image=images/

spring.app.jwtSecretKey=SecretKeyg0w0jgeh0ww0ghh9sehhguwsfqa7qhf9sg9sghwshgfa
spring.app.jwtExprationTimeMs=86400000
spring.ecom.app.jwtCookieName=springBootEcom
#logging.level.org.springframework.security=TRACE

